Document requirement for go 1.19
It appears that Gont requires at least Go 1.19:

    # github.com/stv0g/gont/pkg
    pkg/capture.go:90:15: undefined: atomic.Uint64
    note: module requires Go 1.19
    make: *** [Makefile:8: gontc] Error 2

Add this to the Prerequisites section of the README.

Signed-off-by: Lars Kellogg-Stedman <lars@oddbit.com>